server:
  port: 9999

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: ms1Module
          uri: lb://MS1
          predicates:
            - Path=/ms1/**
        - id: ms2Module
          uri: lb://MS2
          predicates:
            - Path=/ms2/**